export type SampleEvent = { id: number; title: string; art: string; category: string; style: string; day: number; city: string; venue: string; time: string; price: number; host: string; description: string };
export const sampleEvents: SampleEvent[] = [
  { id: 1, title: "An evening of jazz, under the trees", art: "Jazz in the park", category: "Music", style: "music", day: 10, city: "Bengaluru", venue: "Cubbon Park", time: "5:30 PM", price: 499, host: "The Listening Room", description: "Bring a blanket, find a patch of grass, and settle in for an intimate evening of live jazz." },
  { id: 2, title: "Clay, coffee & a little creativity", art: "Make something by hand.", category: "Workshops", style: "craft", day: 11, city: "Bengaluru", venue: "Studio Sunday, Indiranagar", time: "10:00 AM", price: 1200, host: "Studio Sunday", description: "A beginner-friendly hand-building workshop. Make your own small piece and take a coffee break with the group." },
  { id: 3, title: "The neighbourhood Sunday market", art: "Meet your neighbourhood.", category: "Community", style: "community", day: 11, city: "Bengaluru", venue: "JP Nagar Community Grounds", time: "9:00 AM", price: 0, host: "Neighbourhood Collective", description: "Independent makers, fresh bakes, plants and familiar faces. An easy Sunday morning for everyone." },
  { id: 4, title: "Design conversations: starting small", art: "Ideas worth sharing.", category: "Talks", style: "talk", day: 15, city: "Online", venue: "Online", time: "6:30 PM", price: 0, host: "Open Studio", description: "An open conversation about building thoughtful products with small teams. Bring your questions and a notebook." },
  { id: 5, title: "A table for strangers, a taste of home", art: "A seat at the table.", category: "Food & drink", style: "food", day: 17, city: "Bengaluru", venue: "The Courtyard, Shanti Nagar", time: "7:00 PM", price: 850, host: "The Supper Club", description: "A shared dinner inspired by family recipes. Meet new people over a seasonal menu." },
  { id: 6, title: "First light: a lakeside walking group", art: "Take the scenic route.", category: "Outdoors", style: "outdoors", day: 18, city: "Bengaluru", venue: "Sankey Tank", time: "6:30 AM", price: 0, host: "Outside Together", description: "An unhurried morning walk around the lake. Comfortable shoes and a water bottle are all you need." },
];
