const events=[
{id:1,title:'An evening of jazz, under the trees',art:'Jazz in the park',category:'Music',style:'music',day:10,month:'OCT',city:'Bengaluru',venue:'Cubbon Park',time:'5:30 PM',price:499,host:'The Listening Room',description:'Bring a blanket, find a patch of grass, and settle in for an intimate evening of live jazz. A slow Saturday with very good music.'},
{id:2,title:'Clay, coffee & a little creativity',art:'Make something by hand.',category:'Workshops',style:'craft',day:11,month:'OCT',city:'Bengaluru',venue:'Studio Sunday, Indiranagar',time:'10:00 AM',price:1200,host:'Studio Sunday',description:'A beginner-friendly hand-building workshop. Learn the basics, make your own small piece, and take a coffee break with the group. Materials included.'},
{id:3,title:'The neighbourhood Sunday market',art:'Meet your neighbourhood.',category:'Community',style:'community',day:11,month:'OCT',city:'Bengaluru',venue:'JP Nagar Community Grounds',time:'9:00 AM',price:0,host:'Neighbourhood Collective',description:'Independent makers, fresh bakes, plants and familiar faces. An easy Sunday morning for everyone in the neighbourhood.'},
{id:4,title:'Design conversations: starting small',art:'Ideas worth sharing.',category:'Talks',style:'talk',day:15,month:'OCT',city:'Online',venue:'Online · joining link after booking',time:'6:30 PM',price:0,host:'Open Studio',description:'An open conversation about building thoughtful products with small teams. Bring your questions and a notebook.'},
{id:5,title:'A table for strangers, a taste of home',art:'A seat at the table.',category:'Food & drink',style:'food',day:17,month:'OCT',city:'Bengaluru',venue:'The Courtyard, Shanti Nagar',time:'7:00 PM',price:850,host:'The Supper Club',description:'A shared dinner inspired by family recipes. Meet new people over a thoughtfully prepared seasonal menu.'},
{id:6,title:'First light: a lakeside walking group',art:'Take the scenic route.',category:'Outdoors',style:'outdoors',day:18,month:'OCT',city:'Bengaluru',venue:'Sankey Tank',time:'6:30 AM',price:0,host:'Outside Together',description:'An unhurried morning walk around the lake. Comfortable shoes, a water bottle and curiosity are all you need.'}
];
let view='discover',category='All events',query='',city='All locations',saved=new Set(),step=0,draft={title:'',format:'In person',date:'',venue:'',price:'0',capacity:'100',description:''};
const main=document.querySelector('main');const dialog=document.querySelector('#detail');
function notify(message){const n=document.querySelector('#notice');n.textContent=message;n.classList.add('visible');clearTimeout(window.noticeTimer);window.noticeTimer=setTimeout(()=>n.classList.remove('visible'),4500)}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function price(e){return e.price?'₹'+e.price.toLocaleString('en-IN')+' onwards':'Free entry'}
function poster(e){return `<div class="poster ${e.style}"><span class="kicker">${e.host}</span><strong>${e.art}</strong><span class="poster-foot">${e.month} ${e.day} / 2026 · ${e.city}</span></div>`}
function card(e){return `<article class="card"><div class="card-top"><a href="#event-${e.id}" data-event="${e.id}" class="poster-link" aria-label="View ${e.title}">${poster(e)}</a><button class="save ${saved.has(e.id)?'saved':''}" data-save="${e.id}" aria-label="${saved.has(e.id)?'Unsave':'Save'} ${e.title}" aria-pressed="${saved.has(e.id)}">${saved.has(e.id)?'♥':'♡'}</button></div><div class="card-body"><div class="date"><small>${e.month}</small><b>${e.day}</b></div><div><h3><a href="#event-${e.id}" data-event="${e.id}">${e.title}</a></h3><p class="meta">${e.venue} · ${e.time}</p><span class="price">${price(e)}</span></div></div></article>`}
function result(){let list=events.filter(e=>(category==='All events'||(category==='Saved'?saved.has(e.id):category==='Free events'?e.price===0:e.category===category))&&(city==='All locations'||e.city===city)&&`${e.title} ${e.host} ${e.category} ${e.venue}`.toLowerCase().includes(query.toLowerCase()));document.querySelector('#event-grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><h3>No events found</h3><p>Try another search or clear your filters.</p><button class="secondary" id="reset">Clear filters</button></div>';document.querySelector('#count').textContent=`${list.length} ${list.length===1?'event':'events'} · Sample listings`;document.querySelectorAll('.chip').forEach(b=>{b.classList.toggle('selected',b.dataset.category===category);b.setAttribute('aria-pressed',b.dataset.category===category)})}
function discover(){main.innerHTML=`<section class="hero"><div><span class="eyebrow">Go out. Get curious. Find your people.</span><h1>A little more<br><em>out there.</em></h1><p class="intro">Live music, new skills, good conversations.<br>Find something that makes your week.</p></div><div class="hero-art" aria-label="Illustration: Make room for a good weekend"><span class="eyebrow">A note for your weekend</span><b>Make room<br>for a good<br>time.</b><span class="label">Close the tabs. Open a door.</span></div></section><form class="search" id="search-form"><label><span aria-hidden="true">⌕</span><input id="query" type="search" aria-label="Search events" placeholder="An event, an interest, a little inspiration…" value="${escape(query)}"></label><select id="location" aria-label="Event location"><option>All locations</option><option>Bengaluru</option><option>Online</option></select><button class="primary">Find events</button></form><div class="categories" aria-label="Event categories">${['All events','Music','Workshops','Community','Talks','Food & drink','Outdoors','Free events','Saved'].map(c=>`<button class="chip" data-category="${c}" aria-pressed="false">${c}</button>`).join('')}</div><section><div class="section-head"><div><h2>Something for your calendar</h2><p id="count"></p></div><button class="text-button" id="clear">Clear filters ↗</button></div><div class="grid" id="event-grid"></div></section><section class="editor-note"><div><span class="eyebrow">For the people who bring people together</span><h2>Your next event starts here.</h2><p>Create a workspace, build an event, make it happen.</p></div><button class="secondary" data-view="workspace">Explore organising ↗</button></section>`;document.querySelector('#location').value=city;result()}
function tickets(){main.innerHTML=`<section class="page-title"><span class="eyebrow">Your account · Ananya</span><h1>Plans to look forward to.</h1><p class="intro">Your upcoming tickets, all in one place.</p></section><p class="subtle">Preview account · These are sample bookings, not valid admission tickets.</p>${[events[0],events[2]].map(e=>`<article class="panel ticket">${poster(e)}<div><span class="eyebrow">${e.month} ${e.day} · ${e.time} IST</span><h3>${e.title}</h3><p class="meta">${e.venue}</p><span class="status">Sample confirmed booking</span></div><button class="secondary" data-ticket="${e.id}">View ticket ↗</button></article>`).join('')}`}
function workspace(){main.innerHTML=`<section class="page-title"><span class="eyebrow">The Listening Room / Owner workspace · sample data</span><div class="section-head"><div><h1>A good event starts here.</h1><p class="intro">A clear view of what you’re bringing together.</p></div><button class="primary" data-view="create">Create an event +</button></div></section><div class="metrics"><div class="panel metric"><small>Upcoming events</small><b>2</b></div><div class="panel metric"><small>Registrations</small><b>148</b></div><div class="panel metric"><small>Gross ticket sales</small><b>₹58,882</b></div></div><div class="section-head"><h2>Your events</h2><span class="subtle">Approved workspace · Owner preview</span></div><div class="panel table-wrap"><table><thead><tr><th>Event</th><th>Status</th><th>Registrations</th><th>Gross sales</th><th>Action</th></tr></thead><tbody><tr><td><strong>An evening of jazz, under the trees</strong><span class="subtle">10 Oct 2026 · Bengaluru</span></td><td><span class="status">Published</span></td><td>118 / 150</td><td>₹58,882</td><td><button class="text-button" data-event="1">Preview ↗</button></td></tr><tr><td><strong>Sunday listening session</strong><span class="subtle">25 Oct 2026 · Bengaluru</span></td><td><span class="status">Published</span></td><td>30 / 60</td><td>Free</td><td><button class="text-button" data-sample="Event management will be built after the Day 1 preview.">Manage ↗</button></td></tr><tr><td><strong>December acoustic evening</strong><span class="subtle">Date to be confirmed</span></td><td><span class="status draft">Draft</span></td><td>—</td><td>—</td><td><button class="text-button" data-view="create">Start draft ↗</button></td></tr></tbody></table></div><section class="editor-note"><div><h2>Payments collected. Settlements tracked.</h2><p>Organiser payouts will show eligible, scheduled and paid amounts.</p></div><span class="subtle">Payout service is planned</span></section>`}
const steps=['Event basics','Date & location','Tickets','Review'];
function create(){let fields=step===0?`<label class="field">Event title<input name="title" required maxlength="120" value="${escape(draft.title)}" placeholder="Give your event a clear, memorable name"></label><label class="field">Description<textarea name="description" rows="5" required placeholder="What can attendees look forward to?">${escape(draft.description)}</textarea></label>`:step===1?`<label class="field">Format<select name="format"><option${draft.format==='In person'?' selected':''}>In person</option><option${draft.format==='Online'?' selected':''}>Online</option></select></label><label class="field">Start date and time · Asia/Kolkata<input name="date" type="datetime-local" required value="${escape(draft.date)}"></label><label class="field">Venue or online joining URL<input name="venue" required value="${escape(draft.venue)}" placeholder="Location attendees need to know"></label>`:step===2?`<label class="field">General admission price · INR<input name="price" type="number" min="0" step="1" required value="${escape(draft.price)}"></label><label class="field">Capacity<input name="capacity" type="number" min="1" step="1" required value="${escape(draft.capacity)}"></label><p class="subtle">Use 0 for a free event. This wireframe supports one sample ticket type.</p>`:`${Object.entries(draft).map(([k,v])=>`<div class="form-summary"><span>${escape(k)}</span><strong>${escape(v)}</strong></div>`).join('')}<p class="subtle">Preview only: this action will not publish an event. Production publishing requires an approved workspace and owner permission.</p>`;main.innerHTML=`<section class="page-title"><span class="eyebrow">The Listening Room / New event</span><h1>Bring your idea to life.</h1><p class="intro">A few thoughtful details make a great invitation.</p></section><div class="form-layout"><aside><ol class="steps">${steps.map((s,i)=>`<li class="${i===step?'current':''}">${i+1}. ${s}</li>`).join('')}</ol><p class="subtle">Local preview only.<br>Draft resets on page reload.</p></aside><form id="event-form" class="panel"><h2>${steps[step]}</h2>${fields}<div class="form-actions"><button type="button" class="secondary" id="back">${step?'Back':'Back to workspace'}</button><button class="primary">${step===3?'Finish preview':'Continue →'}</button></div></form></div>`}
function render(){document.querySelectorAll('.nav').forEach(b=>{const active=b.dataset.view===view||(view==='create'&&b.dataset.view==='workspace');b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});({discover,tickets,workspace,create}[view])()}
function navigate(next){view=next;render();window.scrollTo(0,0)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b){navigate(b.dataset.view);return}b=e.target.closest('[data-event]');if(b){e.preventDefault();const x=events.find(x=>x.id===+b.dataset.event);document.querySelector('#detail-content').innerHTML=`${poster(x)}<span class="eyebrow">${x.category} · ${x.host}</span><h2>${x.title}</h2><p>${x.description}</p><p>${x.month} ${x.day}, 2026 · ${x.time} IST<br>${x.venue}</p><div class="detail-bottom"><strong>${price(x)}</strong><button class="primary" data-sample="Ticket booking is planned for a later build day. This is a design preview.">${x.price?'Get tickets':'Register free'} ↗</button></div>`;dialog.showModal();return}b=e.target.closest('[data-save]');if(b){const id=+b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);result();return}b=e.target.closest('[data-category]');if(b){category=b.dataset.category;result();return}if(e.target.closest('#clear,#reset')){query='';city='All locations';category='All events';discover();return}if(e.target.closest('.close'))dialog.close();b=e.target.closest('[data-sample]');if(b)notify(b.dataset.sample);b=e.target.closest('[data-ticket]');if(b){const x=events.find(x=>x.id===+b.dataset.ticket);document.querySelector('#detail-content').innerHTML=`<span class="eyebrow">Sample ticket · Not valid for admission</span><h2>${x.title}</h2><p>${x.month} ${x.day}, 2026 · ${x.time} IST<br>${x.venue}</p><div class="panel"><strong>Ananya · General admission × 1</strong><p class="subtle">QR generation, calendar download and cancellation policy will be added with the booking service.</p></div>`;dialog.showModal()}if(e.target.closest('#back')){if(step){capture();step--;create()}else navigate('workspace')}if(e.target.closest('.brand')){e.preventDefault();navigate('discover')}});
function capture(){const f=document.querySelector('#event-form');if(f)for(const [k,v]of new FormData(f))draft[k]=v}
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();query=document.querySelector('#query').value.trim();city=document.querySelector('#location').value;result()}if(e.target.id==='event-form'){e.preventDefault();capture();if(step<3){step++;create()}else{notify('Preview complete. No event was published.');step=0;navigate('workspace')}}});
document.addEventListener('change',e=>{if(e.target.id==='location'){city=e.target.value;result()}});
render();
